spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/seai?currentSchema=seai
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: 30MB

  mail:
    host: smtp.privateemail.com
    port: 587
    username: contacts@seai.co
    password: SEAIseai124
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

document:
  scheduler:
      enabled: true
      cron: "00 00 08 * * ?"

token:
  scheduler:
    enabled: true
    cron: "30 18 10 * * ?"


scanner:
  aws:
    bucket:
      name: "marine-docs1-dev"


urls:
  verify-token: "http://api.seai.co/swagger-ui/index.html#/email-verification-controller/verifyEmail"
  verification-error: "http://api.seai.co/api/v1/users/verify-email/error?message="
  verification-token-resend: "http://api.seai.co/swagger-ui/index.html#/email-verification-controller/resendEmailVerificationToken"
  redirect-to-login: "https://api.seai.co/swagger-ui/index.html#/users-auth-controller/authenticateAndGetToken"
