spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/seai?currentSchema=seai
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: 30MB

  mail:
    host: smtp.privateemail.com
    port: 587
    username: contacts@seai.co
    password: SEAIseai124
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

document:
  scheduler:
      cron: "00 00 08 * * ?"

scanner:
  aws:
    bucket:
      name: "marine-docs1-dev"