spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/seai?currentSchema=seai
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: 30MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  mail:
    host: smtp.privateemail.com
    port: 587
    username: contacts@seai.co
    password: SEAIseai124
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

email-verification:
  token-expiry-period-minutes: 43200 #1 month
  minutes-displayed-in-message: 43200 #1 month

document:
  scheduler:
      enabled: true
      cron: "00 00 08 * * ?"
  patterns:
    certificateNumber: "^\\d{7}$"

token:
  scheduler:
    enabled: true
    cron: "00 00 08 * * ?"


password-token-delete:
  scheduler:
    enabled: true
    cron: "00 00 08 * * ?"

password-verification:
  token-expiry-period-hours: 24
  hours-displayed-in-message: 24

scanner:
  aws:
    bucket:
      name: "marine-docs1-dev"

urls:
  verify-token: "https://api.seai.co/api/v1/users/verify-email?token="
  verification-error: "https://app.seai.co/api/v1/users/verify-email/error?message=" #FIX WHEN WE HAVE FE TO REDIRECT TO SHOW THE MSSAGE
  verification-token-resend: "https://api.seai.co/api/v1/users/resend-email-verification-token?email="
  redirect-to-login: "https://app.seai.co/user/login"

password-urls:
  reset-password: "https://api.seai.co/api/v1/users/reset-password?token="



